export {Login as ScreenLogin} from './SlideLogin'
export {Register as ScreenRegister} from './SlideRegister'
export {Mensagem as ScreenMensagem} from './SlideMensagem'
export {Perfil as ScreenPerfil} from './SlidePerfil'
export { CadMessage as ScreenCadMessage } from './CadMensagem'
export { Camera as SlideCamera } from './SlideCamera'